### ISSUE TITLE
Can't I use the Service Management Panel separately?

### ISSUE THREAD

**Issue by YoonSungHyun-inzent** [VolkovLabs/volkovlabs-balena-app#54]
Hello,

I am running the service through supervisor.
I was impressed by VolkovLabs' wonderful service panel.

Could I use the Service Management Panel separately by any chance?

**Comment by mikhail-vl** [comment]
@YoonSungHyun-inzent, The panel requires tight integration with Data Source to get a list of services and perform actions.

  We are not planning to release the panel separately.
